modLoader="javafml"
loaderVersion="${loader_version_range}"
license="${mod_license}"

[[mods]]
modId="${mod_id}"
version="${mod_version}"
displayName="${mod_name}"
description='''
Magic Storage — All-in-one storage system inspired by Terraria.
Connect Storage Units to a Core, access all items from one terminal,
and craft instantly using accumulated Crafting Energy.
'''

[[dependencies.${mod_id}]]
    modId="neoforge"
    type="required"
    versionRange="[${neo_version},)"
    ordering="NONE"
    side="BOTH"

[[dependencies.${mod_id}]]
    modId="minecraft"
    type="required"
    versionRange="${minecraft_version_range}"
    ordering="NONE"
    side="BOTH"

[[dependencies.${mod_id}]]
    modId="emi"
    type="required"
    versionRange="${emi_version_range}"
    ordering="NONE"
    side="CLIENT"
