from pathlib import Path
import unittest

ROOT = Path(__file__).resolve().parents[1]


class GitHubWorkflowTests(unittest.TestCase):
    def read_required(self, relative_path: str) -> str:
        path = ROOT / relative_path
        self.assertTrue(path.exists(), f"missing {relative_path}")
        return path.read_text()

    def test_ci_workflow_runs_full_project_verification_and_uploads_jar(self):
        text = self.read_required(".github/workflows/ci.yml")
        self.assertIn("name: CI", text)
        self.assertIn("actions/checkout@v7", text)
        self.assertIn("actions/setup-java@v5", text)
        self.assertIn("distribution: temurin", text)
        self.assertIn("java-version: '21'", text)
        self.assertIn("gradle/actions/setup-gradle@v6", text)
        self.assertIn("cache-provider: basic", text)
        self.assertIn("mkdir -p build/ci-logs", text)
        self.assertIn("set -o pipefail", text)
        self.assertIn("./gradlew build --console=plain --no-daemon 2>&1 | tee build/ci-logs/build.log", text)
        self.assertIn("./gradlew runGameTestServer --console=plain --no-daemon 2>&1 | tee build/ci-logs/gametest.log", text)
        self.assertIn("PYTHONDONTWRITEBYTECODE=1 python3 -m unittest discover scripts 2>&1 | tee build/ci-logs/python-unittest.log", text)
        self.assertIn("./gradlew runData --console=plain --no-daemon 2>&1 | tee build/ci-logs/datagen.log", text)
        self.assertIn("git status --porcelain -- src/generated/resources src/main/resources", text)
        self.assertIn("actions/upload-artifact@v7", text)
        self.assertIn("name: magic-storage-ci-logs", text)
        self.assertIn("${{ always() }}", text)
        self.assertIn("build/ci-logs/**", text)
        self.assertIn("run/logs/**", text)
        self.assertIn("build/reports/**", text)
        self.assertIn("build/libs/magic_storage-*.jar", text)
        self.assertIn("contents: read", text)
        self.assertNotIn("runClient", text)
        self.assertNotIn("xvfb-run", text)

    def test_release_workflow_builds_tests_checks_tag_and_publishes_jar(self):
        text = self.read_required(".github/workflows/release.yml")
        self.assertIn("name: Release", text)
        self.assertIn("'v*.*.*'", text)
        self.assertIn("contents: write", text)
        self.assertIn("actions/checkout@v7", text)
        self.assertIn("fetch-depth: 0", text)
        self.assertIn("actions/setup-java@v5", text)
        self.assertIn("gradle/actions/setup-gradle@v6", text)
        self.assertIn("grep '^mod_version=' gradle.properties", text)
        self.assertIn('"v${VERSION}" != "$TAG"', text)
        self.assertIn("./gradlew build --console=plain --no-daemon 2>&1 | tee build/ci-logs/build.log", text)
        self.assertIn("./gradlew runGameTestServer --console=plain --no-daemon 2>&1 | tee build/ci-logs/gametest.log", text)
        self.assertIn("PYTHONDONTWRITEBYTECODE=1 python3 -m unittest discover scripts 2>&1 | tee build/ci-logs/python-unittest.log", text)
        self.assertIn("./gradlew runData --console=plain --no-daemon 2>&1 | tee build/ci-logs/datagen.log", text)
        self.assertIn("git status --porcelain -- src/generated/resources src/main/resources", text)
        self.assertIn("Generate release notes", text)
        self.assertIn("git log --pretty='- %s (%h)'", text)
        self.assertIn("gh release create", text)
        self.assertIn("--notes-file build/release-notes.md", text)
        self.assertIn("name: magic-storage-release-logs", text)
        self.assertIn("build/libs/magic_storage-*.jar", text)
        self.assertIn("GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}", text)
        self.assertNotIn("modrinth", text.lower())
        self.assertNotIn("curseforge", text.lower())
        self.assertNotIn("runClient", text)
        self.assertNotIn("xvfb-run", text)

    def test_public_repo_docs_explain_ci_cd_and_manual_gui_gate(self):
        readme = self.read_required("README.md")
        notes = self.read_required("docs/notes.md")
        agents = self.read_required("AGENTS.md")
        structure = self.read_required("docs/structure.md")
        combined = "\n".join([readme, notes, agents, structure])
        self.assertIn("https://github.com/swear01/Magic_Storage", combined)
        self.assertIn("GitHub Actions", combined)
        self.assertIn("./gradlew runGameTestServer", combined)
        self.assertIn("tag `v<mod_version>`", combined)
        self.assertIn("Prism dev / Computer Use", combined)
        self.assertIn("datagen drift", combined)
        self.assertIn("release notes", combined)
        self.assertIn("Modrinth / CurseForge", self.read_required("docs/roadmap.md"))
        self.assertIn("All Rights Reserved", readme)
        self.assertIn(".github/workflows/", structure)

    def test_client_smoke_workflow_is_manual_only_and_uses_neoforge_runtime_client(self):
        text = self.read_required(".github/workflows/client-smoke.yml")
        self.assertIn("name: Client Smoke", text)
        self.assertIn("workflow_dispatch:", text)
        self.assertNotIn("pull_request", text)
        self.assertNotIn("branches:", text)
        self.assertIn("actions/checkout@v7", text)
        self.assertIn("actions/setup-java@v5", text)
        self.assertIn("gradle/actions/setup-gradle@v6", text)
        self.assertIn("./gradlew build --console=plain --no-daemon", text)
        self.assertIn("cp build/libs/magic_storage-*.jar run/mods/", text)
        self.assertIn("headlesshq/mc-runtime-test@4.4.0", text)
        self.assertIn("mc: '1.21.1'", text)
        self.assertIn("modloader: neoforge", text)
        self.assertIn("regex: '.*neoforge.*'", text)
        self.assertIn("mc-runtime-test: neoforge", text)
        self.assertIn("xvfb: 'true'", text)
        self.assertIn("dummy-assets: 'true'", text)
        self.assertIn("headlessmc-command: '--jvm \"-Djava.awt.headless=true\"'", text)
        self.assertIn("Client Smoke is a boot/resource smoke test, not GUI layout approval", text)


if __name__ == "__main__":
    unittest.main()
